version: "3.7"
services:
    gochain-iconee:
        container_name: gochain-iconee
        image: goloop/gochain-icon:latest
        env_file:
            - ./data/dockerenv/iconee
        volumes:
            - ./data:/testsuite/data
            - ./chain:/testsuite/chain
        ports:
            - "9082:9082"