name: build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run unit tests
        run: ./gradlew clean build optimizedJar

  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Start local Blockchain
        run: docker-compose up -d

      - name: Run integration tests
        run: ./gradlew integrationTest